# Default configuration for riscv32-softmmu

# Uncomment the following lines to disable these optional devices:
#
#CONFIG_PCI_DEVICES=n
CONFIG_SEMIHOSTING=y
CONFIG_ARM_COMPATIBLE_SEMIHOSTING=y

# Boards:
#
CONFIG_SPIKE=y
CONFIG_SIFIVE_E=y
CONFIG_SIFIVE_U=y
CONFIG_RISCV_VIRT=y
CONFIG_OPENTITAN=y
CONFIG_RISCV_CLIC=y
CONFIG_RISCV_SMARTL=y
CONFIG_RISCV_DUMMYH=y
CONFIG_THEAD_ASP_V1=y
CONFIG_RISCV_XIAOHUI=y
